export {default as Header} from "../sections/Header/Header"
export {default as Footer} from "../sections/Footer/Footer"
export {default as Hero} from "../sections/Hero/Hero"
export {default as MostPopular} from "../sections/MostPopular/MostPopular"
export {default as GamingLibrary} from "../sections/GamingLibrary/GamingLibrary"